### PR TITLE
Infrastructure fixes

### LINKED ISSUE #820: Deno shows enableBrowser error
image

### PR DESCRIPTION
**Pull request by SferaDev**
- Add branded types to serializer and deserializer
- Remove incompatible code from ESM and CJS bundles
- Fix #820

### CODE REVIEW

File: packages/client/src/serializer/index.ts [hunk 1]
```diff
@@ -68,12 +68,15 @@ export class Serializer {
 
 const defaultSerializer = new Serializer();
 
-export const serialize = <T>(data: T): string => {
-  return defaultSerializer.toJSON<T>(data);
+type SerializedString<T> = string & { __type: T };
```
Comment (SferaDev) [inline packages/client/src/serializer/index.ts:71]:
```suggestion
type SerializedString<T> = string | (string & { __type: T });
```

File: .changeset/smooth-rabbits-own.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+'@xata.io/plugin-client-cache': patch
+'@xata.io/importer': patch
```
Comment (richardgill) [inline .changeset/smooth-rabbits-own.md:3]: I was expecting to see @xata.io/client here? What am I missing?

**Review by richardgill — APPROVED** [review]
This LGTM
